name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate jobs
        id: set-matrix
        run: |
          delimiter="$(openssl rand -hex 8)"
          touch schematics-features-{1..9}.json
          files=$(echo '{"include": '$(jq -n --argjson files "$(ls *.json | jq -R -s -c 'split("\n")[:-1]')" '$files')'}')
          echo $files >> $GITHUB_OUTPUT
  dynamic-jobs:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.build.outputs.files) }}
    steps:
      - name: Run task
        run: echo "Running task ${{ matrix.file }}"
  clear-up:
    needs: dynamic-jobs
    runs-on: ubuntu-latest
    steps:
      - name: Clear up
        run: "echo \"all good\""
    
